# Generated by Django 2.2.8 on 2020-06-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateEmployee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Account', 'Account'), ('Teacher', 'Teacher')], max_length=10)),
            ],
        ),
    ]
