# Generated by Django 2.2.8 on 2020-07-14 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo'),
        ),
    ]
