# Generated by Django 2.2.8 on 2020-07-14 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200714_0109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentdetailinfo',
            unique_together={('studentID', 'class_id')},
        ),
    ]
