# Generated by Django 2.2.8 on 2020-07-14 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200714_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetailinfo',
            old_name='class_id',
            new_name='class_name',
        ),
        migrations.AlterUniqueTogether(
            name='studentdetailinfo',
            unique_together={('studentID', 'class_name')},
        ),
    ]
