# Generated by Django 2.2.8 on 2020-07-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200714_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='roll',
        ),
        migrations.AddField(
            model_name='studentdetailinfo',
            name='roll',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentdetailinfo',
            unique_together={('roll', 'class_id')},
        ),
    ]
