# Generated by Django 2.2.8 on 2020-07-14 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200714_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetailinfo',
            old_name='studentID',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentDetailInfo'),
        ),
    ]
