# Generated by Django 2.2.8 on 2020-07-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200714_0355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student_id', 'date')},
        ),
    ]
